### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by michaelfedell**
*Description of changes:*
This PR fixes a collection of miscellaneous bugs discovered during test deployments. A few parameters have also had their descriptions/constraints adjusted to be more clear

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelfedell** [comment]
fixes #47

**Review by andrew-glenn — CHANGES_REQUESTED** [review]
Per convo with @michaelfedell  - this PR will be closed in favor of a new one scoping down the changes.

**Comment by michaelfedell** [comment]
Accidental leak of improvement work into this branch so closing - see #51

**Pull request closed without merging**
